services:
  postgres:
    image: postgres:17-alpine
    container_name: ndmu_rmas_postgres
    restart: always
    environment:
      POSTGRES_DB: ndmu_rmas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: ndmu_rmas_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
