@if ($officialForms === [])
    <div class="rounded-2xl border border-gray-200 bg-white p-8 text-center text-sm text-gray-500">No official facilitator forms have been published yet.</div>
@else
    {{-- Shared forms link directly to their existing role templates. --}}
    @include('pages.student.forms.res-026', ['formActor' => 'facilitator'])
    @include('pages.adviser.forms.res-027', ['formActor' => 'facilitator'])
    @include('pages.panelist.forms.res-028', ['formActor' => 'facilitator'])
    @include('pages.student.forms.res-030', ['formActor' => 'facilitator'])
    @include('pages.adviser.forms.res-038', ['formActor' => 'facilitator'])
    @include('pages.student.forms.res-031', ['formActor' => 'facilitator'])
    @include('pages.student.forms.res-032', ['formActor' => 'facilitator'])
    @include('pages.adviser.forms.res-033', ['formActor' => 'facilitator'])
    @include('pages.student.forms.res-034', ['formActor' => 'facilitator'])
    @include('pages.adviser.forms.res-035', ['formActor' => 'facilitator'])
    @include('pages.panelist.forms.res-036', ['formActor' => 'facilitator'])
    @include('pages.panelist.forms.res-037', ['formActor' => 'facilitator'])
    @include('pages.student.forms.res-039', ['formActor' => 'facilitator'])
    @include('pages.adviser.forms.res-040', ['formActor' => 'facilitator'])
    @include('pages.facilitator.forms.res-041')
    @include('pages.student.forms.res-042', ['formActor' => 'facilitator'])
    @include('pages.facilitator.forms.res-043a')
    @include('pages.facilitator.forms.res-043b')
    @include('pages.adviser.forms.res-044', ['formActor' => 'facilitator'])
    @include('pages.facilitator.forms.res-045')
    @include('pages.facilitator.forms.res-046')
    @include('pages.facilitator.forms.res-047')
    @include('pages.student.forms.res-048', ['formActor' => 'facilitator'])
    @include('pages.student.forms.res-049', ['formActor' => 'facilitator'])
@endif
