FROM php:8.4-fpm-alpine3.22

RUN apk add --no-cache icu-dev libzip-dev postgresql17-dev postgresql17-client oniguruma-dev libpng-dev poppler-utils \
    && docker-php-ext-install intl opcache pdo_pgsql zip mbstring gd pcntl

WORKDIR /var/www/html
