<?php

namespace App\Modules\OfficialForms\Services;

class OfficialResearchWorkflowRegistry
{
    /**
     * Complete 25-Form Canonical Definitions & Workflow Specifications.
     *
     * @var array<string, array{
     *     code: string,
     *     title: string,
     *     stage: int,
     *     stage_name: string,
     *     ownership_scope: string,
     *     source_type: ?string,
     *     signature_required: bool,
     *     prerequisites: list<string>,
     *     actions: array<string, array{
     *         label: string,
     *         permission: string,
     *         actor_type: string,
     *         from_states: list<string>,
     *         to_state: string,
     *         signature_required: bool
     *     }>,
     *     next_action: string
     * }>
     */
    public const FORMS = [
        'res-026' => [
            'code' => 'res-026',
            'title' => 'Research Title Approval',
            'stage' => 1,
            'stage_name' => 'Research Title Presentation',
            'ownership_scope' => 'group',
            'source_type' => 'Document:approved_for_presentation',
            'signature_required' => true,
            'prerequisites' => [],
            'actions' => [
                'fill' => [
                    'label' => 'Draft Title Proposal',
                    'permission' => 'forms.res-026.fill',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'draft',
                    'signature_required' => false,
                ],
                'submit' => [
                    'label' => 'Submit for Facilitator Screening',
                    'permission' => 'forms.res-026.submit',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'submitted',
                    'signature_required' => false,
                ],
                'sign_chairperson' => [
                    'label' => 'Sign as Title Panel Chairperson',
                    'permission' => 'evaluations.create',
                    'actor_type' => 'title_panel_chairperson',
                    'from_states' => ['submitted'],
                    'to_state' => 'submitted',
                    'signature_required' => true,
                ],
                'sign_member_1' => [
                    'label' => 'Sign as Title Panel Member 1',
                    'permission' => 'evaluations.create',
                    'actor_type' => 'title_panel_member_1',
                    'from_states' => ['submitted'],
                    'to_state' => 'submitted',
                    'signature_required' => true,
                ],
                'sign_member_2' => [
                    'label' => 'Sign as Title Panel Member 2',
                    'permission' => 'evaluations.create',
                    'actor_type' => 'title_panel_member_2',
                    'from_states' => ['submitted'],
                    'to_state' => 'submitted',
                    'signature_required' => true,
                ],
                'endorse' => [
                    'label' => 'Endorse Title Proposal',
                    'permission' => 'forms.res-026.approve',
                    'actor_type' => 'program_coordinator',
                    'from_states' => ['submitted'],
                    'to_state' => 'endorsed',
                    'signature_required' => true,
                ],
                'approve' => [
                    'label' => 'Approve Title Proposal',
                    'permission' => 'dashboards.dean.view',
                    'actor_type' => 'dean',
                    'from_states' => ['endorsed'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Facilitator explicitly completes the Research Title Presentation milestone.',
        ],
        'res-027' => [
            'code' => 'res-027',
            'title' => 'Research Adviser Invitation',
            'stage' => 1,
            'stage_name' => 'Research Title Presentation',
            'ownership_scope' => 'group',
            'source_type' => 'AdviserRequest',
            'signature_required' => true,
            'prerequisites' => ['res-026'],
            'actions' => [
                'respond' => [
                    'label' => 'Accept Adviser Invitation',
                    'permission' => 'forms.res-027.respond',
                    'actor_type' => 'adviser',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Begin Formulation of Research Proposal',
        ],
        'res-028' => [
            'code' => 'res-028',
            'title' => 'Panelist Invitation',
            'stage' => 3,
            'stage_name' => 'Research Proposal Defense',
            'ownership_scope' => 'defense',
            'source_type' => 'DefensePanelAssignment',
            'signature_required' => true,
            'prerequisites' => ['res-033'],
            'actions' => [
                'respond' => [
                    'label' => 'Accept Panelist Invitation',
                    'permission' => 'forms.res-028.respond',
                    'actor_type' => 'panelist',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Attend Pre-Conference and Proposal Defense',
        ],
        'res-029' => [
            'code' => 'res-029',
            'title' => 'Language Editor Invitation',
            'stage' => 12,
            'stage_name' => 'Language and Technical Editing',
            'ownership_scope' => 'group',
            'source_type' => null,
            'signature_required' => true,
            'prerequisites' => ['res-037'],
            'actions' => [
                'respond' => [
                    'label' => 'Accept Language Editor Assignment',
                    'permission' => 'forms.res-029.respond',
                    'actor_type' => 'language_editor',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Perform Language Editing Review (RES-045)',
        ],
        'res-030' => [
            'code' => 'res-030',
            'title' => 'Request for Change of Research Personnel',
            'stage' => 2,
            'stage_name' => 'Formulation of Research Proposal',
            'ownership_scope' => 'group',
            'source_type' => null,
            'signature_required' => true,
            'prerequisites' => [],
            'actions' => [
                'submit' => [
                    'label' => 'Submit Personnel Change Request',
                    'permission' => 'forms.res-030.submit',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'submitted',
                    'signature_required' => false,
                ],
                'note' => [
                    'label' => 'Note Personnel Change Request',
                    'permission' => 'forms.res-030.approve',
                    'actor_type' => 'program_head',
                    'from_states' => ['submitted', 'in_progress'],
                    'to_state' => 'noted',
                    'signature_required' => true,
                ],
                'approve' => [
                    'label' => 'Approve Personnel Change Request',
                    'permission' => 'forms.res-030.approve',
                    'actor_type' => 'dean',
                    'from_states' => ['submitted', 'noted', 'in_progress'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Await verified Program Head and Dean decision workflow',
        ],
        'res-031' => [
            'code' => 'res-031',
            'title' => 'Adviser Consultation Record',
            'stage' => 2,
            'stage_name' => 'Formulation of Research Proposal',
            'ownership_scope' => 'group',
            'source_type' => 'ConsultationRecord',
            'signature_required' => true,
            'prerequisites' => ['res-027'],
            'actions' => [
                'fill' => [
                    'label' => 'Log Consultation Record',
                    'permission' => 'forms.res-031.fill',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'draft',
                    'signature_required' => false,
                ],
                'sign' => [
                    'label' => 'Sign Consultation Record',
                    'permission' => 'forms.res-031.fill',
                    'actor_type' => 'adviser',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'signed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Continue Proposal Development / Endorsement (RES-033)',
        ],
        'res-032' => [
            'code' => 'res-032',
            'title' => 'Specialist Consultation Sheet',
            'stage' => 2,
            'stage_name' => 'Formulation of Research Proposal',
            'ownership_scope' => 'group',
            'source_type' => 'ConsultationRecord',
            'signature_required' => true,
            'prerequisites' => [],
            'actions' => [
                'fill' => [
                    'label' => 'Log Specialist Consultation',
                    'permission' => 'forms.res-032.fill',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'draft',
                    'signature_required' => false,
                ],
                'sign' => [
                    'label' => 'Sign Specialist Consultation',
                    'permission' => 'forms.res-032.fill',
                    'actor_type' => 'specialist',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Incorporate Specialist Recommendations',
        ],
        'res-033' => [
            'code' => 'res-033',
            'title' => 'Endorsement for Proposal/Final Defense',
            'stage' => 3,
            'stage_name' => 'Research Proposal Defense',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-026', 'res-027'],
            'actions' => [
                'endorse' => [
                    'label' => 'Endorse Proposal/Final Defense',
                    'permission' => 'forms.res-033.endorse',
                    'actor_type' => 'adviser',
                    'from_states' => ['draft', 'submitted'],
                    'to_state' => 'endorsed',
                    'signature_required' => true,
                ],
                'receive' => [
                    'label' => 'Receive Defense Endorsement',
                    'permission' => 'forms.res-033.endorse',
                    'actor_type' => 'program_head',
                    'from_states' => ['endorsed', 'submitted'],
                    'to_state' => 'received',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Await verified paper-copy evidence and Program Head endorsement rules',
        ],
        'res-034' => [
            'code' => 'res-034',
            'title' => 'Defense Pre-Conference Checklist',
            'stage' => 3,
            'stage_name' => 'Research Proposal Defense',
            'ownership_scope' => 'defense',
            'source_type' => 'DefenseSchedule',
            'signature_required' => true,
            'prerequisites' => ['res-033'],
            'actions' => [
                'fill' => [
                    'label' => 'Complete Pre-Conference Checklist',
                    'permission' => 'forms.res-034.fill',
                    'actor_type' => 'panel_chair',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Proceed to Oral Defense Session',
        ],
        'res-035' => [
            'code' => 'res-035',
            'title' => 'Defense Proceedings Record',
            'stage' => 3,
            'stage_name' => 'Research Proposal Defense',
            'ownership_scope' => 'defense',
            'source_type' => 'DefenseSchedule',
            'signature_required' => true,
            'prerequisites' => ['res-034'],
            'actions' => [
                'record' => [
                    'label' => 'Record Proceedings & Deliberation',
                    'permission' => 'forms.res-035.record',
                    'actor_type' => 'panel_chair',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Submit Panel Evaluations (RES-036)',
        ],
        'res-036' => [
            'code' => 'res-036',
            'title' => 'Defense Evaluation Form',
            'stage' => 3,
            'stage_name' => 'Research Proposal Defense',
            'ownership_scope' => 'defense',
            'source_type' => 'DefenseEvaluation',
            'signature_required' => true,
            'prerequisites' => ['res-035'],
            'actions' => [
                'evaluate' => [
                    'label' => 'Submit Defense Evaluation',
                    'permission' => 'forms.res-036.evaluate',
                    'actor_type' => 'panelist',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'submitted',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Consolidate Evaluation Summary (RES-037)',
        ],
        'res-037' => [
            'code' => 'res-037',
            'title' => 'Defense Evaluation Summary Sheet',
            'stage' => 3,
            'stage_name' => 'Research Proposal Defense',
            'ownership_scope' => 'defense',
            'source_type' => 'DefenseEvaluationRound',
            'signature_required' => true,
            'prerequisites' => ['res-036'],
            'actions' => [
                'sign' => [
                    'label' => 'Sign Evaluation Summary & Final Decision',
                    'permission' => 'forms.res-037.sign',
                    'actor_type' => 'panel_chair',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'signed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Prepare Required Revisions (RES-039)',
        ],
        'res-038' => [
            'code' => 'res-038',
            'title' => 'Endorsement of Student Researchers to Adviser',
            'stage' => 1,
            'stage_name' => 'Research Title Presentation',
            'ownership_scope' => 'group',
            'source_type' => 'ResearchClassGroup',
            'signature_required' => true,
            'prerequisites' => ['res-026'],
            'actions' => [
                'endorse' => [
                    'label' => 'Endorse Student Researchers',
                    'permission' => 'forms.res-038.endorse',
                    'actor_type' => 'program_head',
                    'from_states' => ['draft', 'submitted'],
                    'to_state' => 'endorsed',
                    'signature_required' => true,
                ],
                'conforme' => [
                    'label' => 'Conforme Adviser Assignment',
                    'permission' => 'forms.res-038.endorse',
                    'actor_type' => 'adviser',
                    'from_states' => ['endorsed', 'submitted'],
                    'to_state' => 'conformed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Await verified Program Head endorsement and adviser-assignment integration rules',
        ],
        'res-039' => [
            'code' => 'res-039',
            'title' => 'Research Revision Chart',
            'stage' => 4,
            'stage_name' => 'Revision of Research Proposal Paper',
            'ownership_scope' => 'group',
            'source_type' => 'RevisionRequest',
            'signature_required' => true,
            'prerequisites' => ['res-037'],
            'actions' => [
                'fill' => [
                    'label' => 'Submit Revision Actions',
                    'permission' => 'forms.res-039.fill',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'submitted',
                    'signature_required' => false,
                ],
                'sign' => [
                    'label' => 'Verify & Sign Revision Chart',
                    'permission' => 'forms.res-039.fill',
                    'actor_type' => 'adviser',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Endorse Revised Proposal to Research Instructor (RES-040)',
        ],
        'res-040' => [
            'code' => 'res-040',
            'title' => 'Endorsement of Revised Proposal to Research Instructor',
            'stage' => 4,
            'stage_name' => 'Revision of Research Proposal Paper',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-039'],
            'actions' => [
                'endorse' => [
                    'label' => 'Endorse Revised Proposal',
                    'permission' => 'forms.res-040.endorse',
                    'actor_type' => 'adviser',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'endorsed',
                    'signature_required' => true,
                ],
                'receive' => [
                    'label' => 'Receive & Approve Revised Proposal',
                    'permission' => 'forms.res-040.receive',
                    'actor_type' => 'research_instructor',
                    'from_states' => ['draft', 'submitted', 'endorsed', 'in_progress'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Endorse to Program Coordinator (RES-041)',
        ],
        'res-041' => [
            'code' => 'res-041',
            'title' => 'Endorsement to Program Coordinator',
            'stage' => 4,
            'stage_name' => 'Revision of Research Proposal Paper',
            'ownership_scope' => 'group',
            'source_type' => 'OfficialFormInstance',
            'signature_required' => true,
            'prerequisites' => ['res-040'],
            'actions' => [
                'endorse' => [
                    'label' => 'Endorse Proposal to Coordinator',
                    'permission' => 'forms.res-041.endorse',
                    'actor_type' => 'research_instructor',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'endorsed',
                    'signature_required' => true,
                ],
                'receive' => [
                    'label' => 'Receive & Approve Proposal Clearance',
                    'permission' => 'forms.res-041.receive',
                    'actor_type' => 'program_coordinator',
                    'from_states' => ['draft', 'submitted', 'endorsed', 'in_progress'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Request Survey Instrument Validation (RES-042)',
        ],
        'res-042' => [
            'code' => 'res-042',
            'title' => 'Request for Validation of Research Instrument',
            'stage' => 5,
            'stage_name' => 'Validation of Survey Instrument',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-041'],
            'actions' => [
                'submit' => [
                    'label' => 'Submit Instrument Validation Request',
                    'permission' => 'forms.res-042.submit',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'submitted',
                    'signature_required' => false,
                ],
            ],
            'next_action' => 'Assign an eligible validator, then create request-scoped RES-043A/B outputs',
        ],
        'res-043a' => [
            'code' => 'res-043a',
            'title' => 'Instrument Item Validation Rating Sheet',
            'stage' => 5,
            'stage_name' => 'Validation of Survey Instrument',
            'ownership_scope' => 'group',
            'source_type' => 'OfficialFormInstance',
            'signature_required' => true,
            'prerequisites' => ['res-042'],
            'actions' => [
                'validate' => [
                    'label' => 'Complete Instrument Rating',
                    'permission' => 'forms.res-043a.validate',
                    'actor_type' => 'instrument_validator',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Generate Validation Summary Sheet (RES-043B)',
        ],
        'res-043b' => [
            'code' => 'res-043b',
            'title' => 'Validation Summary Sheet',
            'stage' => 5,
            'stage_name' => 'Validation of Survey Instrument',
            'ownership_scope' => 'group',
            'source_type' => 'OfficialFormInstance',
            'signature_required' => true,
            'prerequisites' => ['res-043a'],
            'actions' => [
                'validate' => [
                    'label' => 'Certify Instrument Validation Summary',
                    'permission' => 'forms.res-043b.validate',
                    'actor_type' => 'instrument_validator',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Proceed to Data Gathering Endorsement (RES-044)',
        ],
        'res-044' => [
            'code' => 'res-044',
            'title' => 'Data Gathering Endorsement',
            'stage' => 7,
            'stage_name' => 'Data Gathering',
            'ownership_scope' => 'group',
            'source_type' => 'OfficialFormInstance',
            'signature_required' => true,
            'prerequisites' => ['res-043b'],
            'actions' => [],
            'next_action' => 'Await verified prerequisite and multi-signature institutional rules',
        ],
        'res-045' => [
            'code' => 'res-045',
            'title' => 'Language Editing Certificate',
            'stage' => 12,
            'stage_name' => 'Language and Technical Editing',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-037'],
            'actions' => [
                'certify' => [
                    'label' => 'Issue Language Editing Certificate',
                    'permission' => 'forms.res-045.certify',
                    'actor_type' => 'language_editor',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Proceed to Technical Editing Certification (RES-046)',
        ],
        'res-046' => [
            'code' => 'res-046',
            'title' => 'Technical Editing Certificate',
            'stage' => 12,
            'stage_name' => 'Language and Technical Editing',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-045'],
            'actions' => [
                'certify' => [
                    'label' => 'Issue Technical Editing Certificate',
                    'permission' => 'forms.res-046.certify',
                    'actor_type' => 'technical_editor',
                    'from_states' => ['draft', 'submitted', 'in_progress', 'pending_action'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Proceed to Paper Reproduction Endorsement (RES-047)',
        ],
        'res-047' => [
            'code' => 'res-047',
            'title' => 'Paper Reproduction Endorsement',
            'stage' => 12,
            'stage_name' => 'Language and Technical Editing',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-045', 'res-046'],
            'actions' => [
                'endorse' => [
                    'label' => 'Endorse Paper Reproduction',
                    'permission' => 'forms.res-047.endorse',
                    'actor_type' => 'adviser',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'endorsed',
                    'signature_required' => true,
                ],
                'approve' => [
                    'label' => 'Approve Reproduction Clearance as Dean',
                    'permission' => 'forms.res-047.approve',
                    'actor_type' => 'dean',
                    'from_states' => ['draft', 'submitted', 'endorsed', 'in_progress'],
                    'to_state' => 'approved',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Execute Self & Peer Evaluations (RES-048) & Authorship Certificate (RES-049)',
        ],
        'res-048' => [
            'code' => 'res-048',
            'title' => 'Self & Peer Evaluation Form',
            'stage' => 13,
            'stage_name' => 'Submission of Final Copy of Research Paper',
            'ownership_scope' => 'user',
            'source_type' => null,
            'signature_required' => true,
            'prerequisites' => ['res-047'],
            'actions' => [
                'fill' => [
                    'label' => 'Submit Self & Peer Evaluation',
                    'permission' => 'forms.res-048.fill',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft'],
                    'to_state' => 'submitted',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Sign Authentic Authorship Certificate (RES-049)',
        ],
        'res-049' => [
            'code' => 'res-049',
            'title' => 'Certificate of Authentic Authorship',
            'stage' => 13,
            'stage_name' => 'Submission of Final Copy of Research Paper',
            'ownership_scope' => 'group',
            'source_type' => 'Document',
            'signature_required' => true,
            'prerequisites' => ['res-047', 'res-048'],
            'actions' => [
                'sign_authorship' => [
                    'label' => 'Sign Authentic Authorship Certificate',
                    'permission' => 'forms.res-049.sign',
                    'actor_type' => 'student_researcher',
                    'from_states' => ['draft', 'submitted', 'in_progress'],
                    'to_state' => 'completed',
                    'signature_required' => true,
                ],
            ],
            'next_action' => 'Final Research Paper Archived in Repository',
        ],
    ];

    /** @return array<string, mixed>|null */
    public static function getFormDefinition(string $code): ?array
    {
        return self::FORMS[strtolower($code)] ?? null;
    }

    /** @return array<string, mixed>|null */
    public static function getActionSpec(string $formCode, string $action): ?array
    {
        $form = self::getFormDefinition($formCode);

        return $form['actions'][strtolower($action)] ?? null;
    }
}
