<?php

namespace App\Modules\AuditLogs\Support;

final class AuditEvent
{
    /** @var list<string> */
    public const ALL = [
        'workspace.switched',
        'user.registered',
        'user.created',
        'user.approved',
        'user.rejected',
        'user.activated',
        'user.suspended',
        'user.access-updated',
        'role.created',
        'role.updated',
        'role.deleted',
        'system-settings.updated',
        'auth.login.succeeded',
        'auth.login.failed',
        'auth.login.blocked',
        'auth.logout',
        'auth.password-reset.completed',
        'auth.email-verified',
        'class.created',
        'class.updated',
        'class.join-request.submitted',
        'class.join-request.approved',
        'class.join-request.rejected',
        'research-group.created',
        'research-group.renamed',
        'research-group.disbanded',
        'research-group.member-assigned',
        'research-group.leader-assigned',
        'adviser.assignment.created',
        'adviser.assignment.removed',
        'adviser.invitation.sent',
        'adviser.invitation.cancelled',
        'adviser.invitation.accepted',
        'adviser.invitation.rejected',
        'document.submitted',
        'document.downloaded',
        'document.viewed',
        'document.review.decision-recorded',
        'document.review.corrected',
        'consultation.requested',
        'consultation.approved',
        'consultation.rejected',
        'consultation.cancelled',
        'consultation.rescheduled',
        'consultation.completed',
        'consultation.record.corrected',
        'revision.started',
        'revision.submitted',
        'revision.transitioned',
        'revision.resolved',
        'revision.reopened',
        'research.milestone.updated',
        'research.milestone.corrected',
        'official-form.created',
        'official-form.submitted',
        'official-form.action-recorded',
        'official-form.actor-assigned',
        'official-form.actor-removed',
        'signature.enrolled',
        'signature.removed',
        'signature.applied',
        'defense.scheduled',
        'defense.rescheduled',
        'defense.cancelled',
        'defense.panel.assigned',
        'defense.panel.removed',
        'defense.completed',
        'evaluation.round.opened',
        'evaluation.draft-saved',
        'evaluation.submitted',
        'evaluation.round.finalized',
        'evaluation.results.released',
    ];

    public static function isAllowed(string $event): bool
    {
        return in_array($event, self::ALL, true);
    }
}
