<?php

return [
    // Only deletion is protected. Permissions on every role remain editable;
    // critical administrator capabilities are guarded by the domain action.
    'protected_roles' => ['administrator'],

    'legacy_role_aliases' => [
        'system-administrator' => 'administrator',
        'student-researcher' => 'student',
        'research-adviser' => 'thesis-adviser',
        'panelist' => 'panel-member',
        'college-dean' => 'dean',
    ],

    'roles' => [
        'administrator' => [
            'label' => 'Administrator',
            'description' => 'Manages system users, access control, configuration, auditing, and reporting.',
            'user_type' => 'admin',
            'permissions' => ['dashboards.admin.view', 'research.view-all', 'progress.view-all', 'documents.download', 'documents.download-any', 'defenses.view', 'reports.view', 'reports.export', 'users.manage', 'roles.manage', 'permissions.manage', 'audit-logs.view', 'settings.manage', 'notifications.broadcast'],
        ],
        'faculty' => [
            'label' => 'Faculty',
            'description' => 'Legacy faculty identity role retained for compatibility. Faculty identity now comes from the account type.',
            'user_type' => 'faculty',
            'is_assignable' => false,
            'permissions' => [],
        ],
        'student' => [
            'label' => 'Student',
            'description' => 'Student researcher access to owned records and enrolled classes.',
            'user_type' => 'student',
            'permissions' => ['dashboards.student.view', 'research.view-own', 'progress.view-own', 'research.create', 'research.update-own', 'proposal.submit', 'documents.upload', 'documents.download', 'consultations.request', 'classes.join', 'classes.view-enrolled', 'revisions.resolve', 'defenses.view', 'evaluations.view-own', 'forms.res-026.view', 'forms.res-026.fill', 'forms.res-026.submit', 'forms.res-030.view', 'forms.res-030.submit', 'forms.res-031.view', 'forms.res-031.fill', 'forms.res-032.view', 'forms.res-032.fill', 'forms.res-034.view', 'forms.res-039.view', 'forms.res-039.fill', 'forms.res-042.view', 'forms.res-042.submit', 'forms.res-048.view', 'forms.res-048.fill', 'forms.res-049.view', 'forms.res-049.sign'],
        ],
        'research-facilitator' => [
            'label' => 'Research Facilitator',
            'description' => 'Coordinates research classes, groups, reviews, defenses, and reporting.',
            'user_type' => 'faculty',
            'permissions' => ['dashboards.facilitator.view', 'research.view-all', 'progress.view-owned-classes', 'progress.manage-owned-classes', 'progress.override-order', 'proposal.review', 'proposal.approve', 'documents.review', 'documents.download', 'revisions.create', 'defenses.view', 'defenses.manage', 'evaluations.create', 'evaluations.release', 'evaluations.view-assigned', 'reports.view', 'reports.export', 'notifications.broadcast', 'classes.create', 'classes.view-own', 'classes.manage-join-requests', 'classes.manage-groups', 'classes.assign-advisers', 'forms.res-026.view', 'forms.res-026.approve', 'forms.res-027.view', 'forms.res-028.view', 'forms.res-030.view', 'forms.res-030.approve', 'forms.res-031.view', 'forms.res-032.view', 'forms.res-033.view', 'forms.res-034.view', 'forms.res-035.view', 'forms.res-036.view', 'forms.res-037.view', 'forms.res-038.view', 'forms.res-038.endorse', 'forms.res-039.view', 'forms.res-040.view', 'forms.res-041.view', 'forms.res-042.view', 'forms.res-044.view', 'forms.res-047.view', 'forms.res-048.view', 'forms.res-049.view'],
        ],
        'program-coordinator' => [
            'label' => 'Program Coordinator',
            'description' => 'Coordinates program-level research activity and approvals.',
            'user_type' => 'faculty',
            'permissions' => ['dashboards.facilitator.view', 'research.view-college', 'research.approve', 'proposal.approve', 'documents.review', 'documents.download', 'defenses.view', 'reports.view', 'reports.export', 'forms.res-026.view', 'forms.res-026.approve', 'forms.res-041.view', 'forms.res-041.receive'],
        ],
        'thesis-adviser' => [
            'label' => 'Thesis Adviser',
            'description' => 'Advises assigned research groups and reviews their work.',
            'user_type' => 'faculty',
            'permissions' => ['dashboards.adviser.view', 'classes.serve-as-adviser', 'research.view-assigned', 'progress.view-assigned', 'proposal.review', 'documents.upload', 'documents.review', 'documents.download', 'consultations.manage-assigned', 'revisions.create', 'revisions.resolve', 'defenses.view', 'evaluations.view-assigned', 'classes.view-assigned', 'forms.res-026.view', 'forms.res-027.view', 'forms.res-027.respond', 'forms.res-031.view', 'forms.res-031.sign', 'forms.res-032.view', 'forms.res-032.sign', 'forms.res-033.view', 'forms.res-033.endorse', 'forms.res-034.view', 'forms.res-035.view', 'forms.res-035.record', 'forms.res-038.view', 'forms.res-040.view', 'forms.res-040.endorse', 'forms.res-042.view', 'forms.res-044.view', 'forms.res-044.endorse', 'forms.res-047.view', 'forms.res-047.endorse', 'forms.res-048.view', 'forms.res-049.view'],
        ],
        'panel-member' => [
            'label' => 'Panel Member',
            'description' => 'Reviews and evaluates assigned research defenses.',
            'user_type' => 'faculty',
            'permissions' => ['dashboards.panelist.view', 'research.view-assigned', 'documents.download', 'defenses.view', 'evaluations.create', 'evaluations.view-own', 'evaluations.view-assigned', 'forms.res-028.view', 'forms.res-028.respond', 'forms.res-034.view', 'forms.res-035.view', 'forms.res-036.view', 'forms.res-036.evaluate', 'forms.res-037.view', 'forms.res-037.sign', 'forms.res-039.view', 'forms.res-039.approve', 'forms.res-044.view'],
        ],
        'department-chair' => [
            'label' => 'Department Chair',
            'description' => 'Provides department-level research oversight and approvals.',
            'user_type' => 'faculty',
            'permissions' => ['dashboards.dean.view', 'research.view-college', 'research.approve', 'proposal.approve', 'documents.download', 'defenses.view', 'evaluations.view-assigned', 'reports.view', 'forms.res-047.view'],
        ],
        'dean' => [
            'label' => 'Dean',
            'description' => 'Provides college-level research oversight, approval, and reporting.',
            'user_type' => 'faculty',
            'permissions' => ['dashboards.dean.view', 'research.view-college', 'research.approve', 'proposal.approve', 'documents.download', 'defenses.view', 'evaluations.view-assigned', 'reports.view', 'reports.export', 'forms.res-047.view', 'forms.res-047.approve'],
        ],
        'research-instructor' => [
            'label' => 'Research Instructor',
            'description' => 'Instructor for Capstone/Research methods courses providing academic endorsements.',
            'user_type' => 'faculty',
            'is_assignable' => true,
            'permissions' => ['forms.res-040.view', 'forms.res-040.receive', 'forms.res-041.view', 'forms.res-041.fill', 'forms.res-041.endorse'],
        ],
        'language-editor' => [
            'label' => 'Language Editor',
            'description' => 'Specialist for manuscript language editing review and certification.',
            'user_type' => 'faculty',
            'is_assignable' => true,
            'permissions' => ['forms.res-029.view', 'forms.res-029.respond', 'forms.res-045.view', 'forms.res-045.certify'],
        ],
        'technical-editor' => [
            'label' => 'Technical Editor',
            'description' => 'Specialist for manuscript technical editing review and certification.',
            'user_type' => 'faculty',
            'is_assignable' => true,
            'permissions' => ['forms.res-046.view', 'forms.res-046.certify'],
        ],
        'instrument-validator' => [
            'label' => 'Instrument Validator',
            'description' => 'Specialist for survey instrument item validation and rating.',
            'user_type' => 'faculty',
            'is_assignable' => true,
            'permissions' => ['forms.res-042.view', 'forms.res-043a.view', 'forms.res-043a.validate', 'forms.res-043b.view', 'forms.res-043b.validate'],
        ],
    ],

    /*
    | Permission names are stable application capabilities. Administrators may
    | combine them into custom roles, but cannot create arbitrary permissions.
    */
    'permissions' => [
        'Dashboards' => [
            'dashboards.student.view' => ['label' => 'Open Student Dashboard', 'description' => 'Open the student research workspace.', 'scope' => 'Student workspace'],
            'dashboards.adviser.view' => ['label' => 'Open Adviser Dashboard', 'description' => 'Open the thesis adviser workspace.', 'scope' => 'Adviser workspace'],
            'dashboards.facilitator.view' => ['label' => 'Open Facilitator Dashboard', 'description' => 'Open the research facilitator workspace.', 'scope' => 'Facilitator workspace'],
            'dashboards.panelist.view' => ['label' => 'Open Panel Dashboard', 'description' => 'Open the panel member workspace.', 'scope' => 'Panel workspace'],
            'dashboards.dean.view' => ['label' => 'Open Oversight Dashboard', 'description' => 'Open the chair or dean oversight workspace.', 'scope' => 'College oversight workspace'],
            'dashboards.admin.view' => ['label' => 'Open Admin Dashboard', 'description' => 'Open the system administration workspace.', 'scope' => 'Administration workspace'],
        ],
        'Administration' => [
            'users.manage' => ['label' => 'Manage Users', 'description' => 'Create accounts, approve registrations, and manage account status.', 'scope' => 'All managed user accounts'],
            'roles.manage' => ['label' => 'Manage Roles', 'description' => 'Create, update, and delete custom access roles.', 'scope' => 'Custom roles only'],
            'permissions.manage' => ['label' => 'Assign Permissions', 'description' => 'Select catalog permissions for custom roles.', 'scope' => 'Permission catalog'],
            'audit-logs.view' => ['label' => 'View Audit Logs', 'description' => 'Review recorded security and administrative events.', 'scope' => 'System audit records'],
            'settings.manage' => ['label' => 'Manage Settings', 'description' => 'Manage protected system configuration.', 'scope' => 'System settings'],
            'notifications.broadcast' => ['label' => 'Broadcast Notifications', 'description' => 'Send official notifications to system users.', 'scope' => 'Authorized recipients'],
        ],
        'Research' => [
            'research.create' => ['label' => 'Create Research', 'description' => 'Create a research record for an authorized group.', 'scope' => 'Owned research'],
            'research.update-own' => ['label' => 'Update Own Research', 'description' => 'Update research owned by the user or their group.', 'scope' => 'Owned research'],
            'research.view-own' => ['label' => 'View Own Research', 'description' => 'View research owned by the user or their group.', 'scope' => 'Owned research'],
            'research.view-assigned' => ['label' => 'View Assigned Research', 'description' => 'View research explicitly assigned to the user.', 'scope' => 'Assigned research'],
            'research.view-college' => ['label' => 'View College Research', 'description' => 'View research within the configured CEAC college.', 'scope' => 'CEAC'],
            'research.view-all' => ['label' => 'View All Research', 'description' => 'View all research records allowed by administrative policy.', 'scope' => 'System research records'],
            'research.approve' => ['label' => 'Approve Research', 'description' => 'Approve research records at the authorized review level.', 'scope' => 'Assigned review scope'],
            'progress.view-own' => ['label' => 'View Own Group Progress', 'description' => 'View milestone progress for a current or verified former research group.', 'scope' => 'Own research group'],
            'progress.view-assigned' => ['label' => 'View Assigned Group Progress', 'description' => 'View milestone progress for assigned advisee groups.', 'scope' => 'Assigned research groups'],
            'progress.view-owned-classes' => ['label' => 'View Owned Class Progress', 'description' => 'Monitor milestones for groups in classes owned by the facilitator.', 'scope' => 'Owned research classes'],
            'progress.manage-owned-classes' => ['label' => 'Manage Owned Class Progress', 'description' => 'Manage milestone state, dates, remarks, and evidence for groups in owned classes.', 'scope' => 'Owned research classes'],
            'progress.override-order' => ['label' => 'Override Milestone Order', 'description' => 'Perform a justified, audited out-of-order milestone transition in an owned class.', 'scope' => 'Owned research classes'],
            'progress.view-all' => ['label' => 'View All Research Progress', 'description' => 'View research progress for administrative oversight without mutation authority.', 'scope' => 'System research groups'],
        ],
        'Classes' => [
            'classes.serve-as-adviser' => ['label' => 'Serve as Adviser', 'description' => 'Allow assignment as the adviser of a research group.', 'scope' => 'Assigned research groups'],
            'classes.create' => ['label' => 'Create Classes', 'description' => 'Create and manage owned Capstone classes.', 'scope' => 'Owned classes'],
            'classes.join' => ['label' => 'Join Classes', 'description' => 'Request enrollment in a research class.', 'scope' => 'Student account'],
            'classes.view-enrolled' => ['label' => 'View Enrolled Classes', 'description' => 'View classes in which the user is enrolled.', 'scope' => 'Enrolled classes'],
            'classes.view-own' => ['label' => 'View Owned Classes', 'description' => 'View classes created by the facilitator.', 'scope' => 'Owned classes'],
            'classes.view-assigned' => ['label' => 'View Assigned Classes', 'description' => 'View classes or groups assigned to an adviser.', 'scope' => 'Assigned classes'],
            'classes.manage-join-requests' => ['label' => 'Manage Join Requests', 'description' => 'Approve or reject student class requests.', 'scope' => 'Owned classes'],
            'classes.manage-groups' => ['label' => 'Manage Research Groups', 'description' => 'Create groups and assign enrolled students.', 'scope' => 'Owned classes'],
            'classes.assign-advisers' => ['label' => 'Assign Advisers', 'description' => 'Assign eligible advisers to research groups.', 'scope' => 'Owned classes'],
        ],
        'Documents and Proposals' => [
            'proposal.submit' => ['label' => 'Submit Proposals', 'description' => 'Submit research proposals for review.', 'scope' => 'Owned research'],
            'proposal.review' => ['label' => 'Review Proposals', 'description' => 'Review proposals within an authorized assignment.', 'scope' => 'Assigned research'],
            'proposal.approve' => ['label' => 'Approve Proposals', 'description' => 'Record an authorized proposal approval.', 'scope' => 'Assigned review scope'],
            'documents.upload' => ['label' => 'Upload Documents', 'description' => 'Upload validated PDF or DOCX research documents.', 'scope' => 'Owned or assigned research'],
            'documents.review' => ['label' => 'Review Documents', 'description' => 'Review documents from assigned researchers.', 'scope' => 'Assigned research'],
            'documents.download' => ['label' => 'Download Documents', 'description' => 'Download documents after record-scoped authorization.', 'scope' => 'Authorized documents'],
            'documents.download-any' => ['label' => 'Download Any Document', 'description' => 'Administrative download access subject to policy checks.', 'scope' => 'System documents'],
        ],
        'Workflow' => [
            'consultations.request' => ['label' => 'Request Consultations', 'description' => 'Book consultation requests with an assigned adviser.', 'scope' => 'Owned research'],
            'consultations.manage-assigned' => ['label' => 'Manage Consultations', 'description' => 'Manage consultation requests from assigned students.', 'scope' => 'Assigned students'],
            'revisions.create' => ['label' => 'Create Revisions', 'description' => 'Issue revision requirements for reviewed research.', 'scope' => 'Assigned research'],
            'revisions.resolve' => ['label' => 'Resolve Revisions', 'description' => 'Submit or resolve authorized revision work.', 'scope' => 'Owned or assigned research'],
            'defenses.view' => ['label' => 'View Defenses', 'description' => 'View defense schedules within the user assignment.', 'scope' => 'Authorized defenses'],
            'defenses.manage' => ['label' => 'Manage Defenses', 'description' => 'Create and manage defense schedules.', 'scope' => 'Authorized defenses'],
            'evaluations.create' => ['label' => 'Create Evaluations', 'description' => 'Submit an evaluation for an assigned defense.', 'scope' => 'Assigned defenses'],
            'evaluations.release' => ['label' => 'Release Evaluation Results', 'description' => 'Release finalized defense evaluation summary to students and advisers.', 'scope' => 'Owned research classes'],
            'evaluations.view-own' => ['label' => 'View Own Evaluations', 'description' => 'View evaluations created by or released to the user.', 'scope' => 'Own evaluations'],
            'evaluations.view-assigned' => ['label' => 'View Assigned Evaluations', 'description' => 'View evaluations for assigned research or defenses.', 'scope' => 'Assigned evaluations'],
        ],
        'Reports' => [
            'reports.view' => ['label' => 'View Reports', 'description' => 'View authorized research and operational reports.', 'scope' => 'Authorized report scope'],
            'reports.export' => ['label' => 'Export Reports', 'description' => 'Export authorized reports without bypassing record scope.', 'scope' => 'Authorized report scope'],
        ],
        'Official Research Forms' => [
            'forms.res-026.view' => ['label' => 'View RES-026 Title Approval', 'description' => 'View Title Approval form instance.', 'scope' => 'Group scope'],
            'forms.res-026.fill' => ['label' => 'Fill RES-026 Title Approval', 'description' => 'Draft proposed topics for Title Approval.', 'scope' => 'Group scope'],
            'forms.res-026.submit' => ['label' => 'Submit RES-026 Title Approval', 'description' => 'Submit Title Approval for review.', 'scope' => 'Group scope'],
            'forms.res-026.approve' => ['label' => 'Approve RES-026 Title Approval', 'description' => 'Approve or sign the Research Title Approval form.', 'scope' => 'Program Coordinator scope'],
            'forms.res-027.view' => ['label' => 'View RES-027 Adviser Invitation', 'description' => 'View Adviser Invitation form.', 'scope' => 'Assigned scope'],
            'forms.res-027.respond' => ['label' => 'Respond to RES-027 Adviser Invitation', 'description' => 'Accept or decline adviser invitation.', 'scope' => 'Assigned scope'],
            'forms.res-028.view' => ['label' => 'View RES-028 Panelist Invitation', 'description' => 'View Panelist Invitation form.', 'scope' => 'Assigned scope'],
            'forms.res-028.respond' => ['label' => 'Respond to RES-028 Panelist Invitation', 'description' => 'Accept or decline panelist invitation.', 'scope' => 'Assigned scope'],
            'forms.res-029.view' => ['label' => 'View RES-029 Language Editor Invitation', 'description' => 'View Language Editor Invitation form.', 'scope' => 'Assigned scope'],
            'forms.res-029.respond' => ['label' => 'Respond to RES-029 Language Editor Invitation', 'description' => 'Accept or decline language editor invitation.', 'scope' => 'Assigned scope'],
            'forms.res-030.view' => ['label' => 'View RES-030 Change Request', 'description' => 'View Personnel Change Request form.', 'scope' => 'Group scope'],
            'forms.res-030.submit' => ['label' => 'Submit RES-030 Change Request', 'description' => 'Submit Personnel Change Request.', 'scope' => 'Group scope'],
            'forms.res-030.approve' => ['label' => 'Approve RES-030 Change Request', 'description' => 'Approve Personnel Change Request.', 'scope' => 'Assigned scope'],
            'forms.res-031.view' => ['label' => 'View RES-031 Adviser Consultation', 'description' => 'View Consultation Record with Adviser.', 'scope' => 'Group scope'],
            'forms.res-031.fill' => ['label' => 'Fill RES-031 Adviser Consultation', 'description' => 'Log topics and recommendations for adviser consultation.', 'scope' => 'Group scope'],
            'forms.res-031.sign' => ['label' => 'Sign RES-031 Adviser Consultation', 'description' => 'Sign adviser consultation record.', 'scope' => 'Assigned scope'],
            'forms.res-032.view' => ['label' => 'View RES-032 Specialist Consultation', 'description' => 'View Consultation Sheet with Specialist.', 'scope' => 'Group scope'],
            'forms.res-032.fill' => ['label' => 'Fill RES-032 Specialist Consultation', 'description' => 'Log specialist recommendations.', 'scope' => 'Group scope'],
            'forms.res-032.sign' => ['label' => 'Sign RES-032 Specialist Consultation', 'description' => 'Sign specialist consultation sheet.', 'scope' => 'Assigned scope'],
            'forms.res-033.view' => ['label' => 'View RES-033 Defense Endorsement', 'description' => 'View Defense Endorsement form.', 'scope' => 'Group scope'],
            'forms.res-033.endorse' => ['label' => 'Endorse RES-033 Defense', 'description' => 'Issue adviser endorsement for defense.', 'scope' => 'Assigned scope'],
            'forms.res-034.view' => ['label' => 'View RES-034 Defense Pre-Conference', 'description' => 'View Pre-Conference checklist & notes.', 'scope' => 'Group scope'],
            'forms.res-034.fill' => ['label' => 'Fill RES-034 Defense Pre-Conference', 'description' => 'Record pre-conference findings.', 'scope' => 'Assigned scope'],
            'forms.res-035.view' => ['label' => 'View RES-035 Defense Proceedings', 'description' => 'View Defense Proceedings record.', 'scope' => 'Group scope'],
            'forms.res-035.record' => ['label' => 'Record RES-035 Defense Proceedings', 'description' => 'Record and sign defense proceedings.', 'scope' => 'Assigned scope'],
            'forms.res-036.view' => ['label' => 'View RES-036 Defense Evaluation', 'description' => 'View Defense Evaluation rubric.', 'scope' => 'Assigned scope'],
            'forms.res-036.evaluate' => ['label' => 'Evaluate RES-036 Defense', 'description' => 'Submit individual panelist defense rating.', 'scope' => 'Assigned scope'],
            'forms.res-037.view' => ['label' => 'View RES-037 Evaluation Summary', 'description' => 'View Evaluation Summary of Defense.', 'scope' => 'Group scope'],
            'forms.res-037.sign' => ['label' => 'Sign RES-037 Evaluation Summary', 'description' => 'Sign final evaluation summary.', 'scope' => 'Assigned scope'],
            'forms.res-038.view' => ['label' => 'View RES-038 Student Endorsement', 'description' => 'View Endorsement of Student Researchers to Adviser.', 'scope' => 'Assigned scope'],
            'forms.res-038.endorse' => ['label' => 'Endorse RES-038 Students', 'description' => 'Issue facilitator endorsement of student researchers.', 'scope' => 'Assigned scope'],
            'forms.res-039.view' => ['label' => 'View RES-039 Revision Chart', 'description' => 'View Research Revision Chart.', 'scope' => 'Group scope'],
            'forms.res-039.fill' => ['label' => 'Fill RES-039 Revision Chart', 'description' => 'Record compliance for required revisions.', 'scope' => 'Group scope'],
            'forms.res-039.approve' => ['label' => 'Approve RES-039 Revision Chart', 'description' => 'Approve compliance on revision chart.', 'scope' => 'Assigned scope'],
            'forms.res-040.view' => ['label' => 'View RES-040 Instructor Endorsement', 'description' => 'View Endorsement to Research Instructor.', 'scope' => 'Assigned scope'],
            'forms.res-040.endorse' => ['label' => 'Endorse RES-040 to Instructor', 'description' => 'Adviser endorses revised proposal to Research Instructor.', 'scope' => 'Assigned scope'],
            'forms.res-040.receive' => ['label' => 'Receive RES-040 Instructor Endorsement', 'description' => 'Research Instructor receives proposal endorsement.', 'scope' => 'Assigned scope'],
            'forms.res-041.view' => ['label' => 'View RES-041 Coordinator Endorsement', 'description' => 'View Endorsement to Program Coordinator.', 'scope' => 'Class scope'],
            'forms.res-041.fill' => ['label' => 'Fill RES-041 Coordinator Endorsement', 'description' => 'Compile class research proposal list for coordinator.', 'scope' => 'Class scope'],
            'forms.res-041.endorse' => ['label' => 'Endorse RES-041 to Coordinator', 'description' => 'Research Instructor endorses proposal list to Program Coordinator.', 'scope' => 'Class scope'],
            'forms.res-041.receive' => ['label' => 'Receive RES-041 Coordinator Endorsement', 'description' => 'Program Coordinator receives proposal endorsement list.', 'scope' => 'Class scope'],
            'forms.res-042.view' => ['label' => 'View RES-042 Validation Request', 'description' => 'View Request for Instrument Validation.', 'scope' => 'Group scope'],
            'forms.res-042.submit' => ['label' => 'Submit RES-042 Validation Request', 'description' => 'Submit request for instrument validation.', 'scope' => 'Group scope'],
            'forms.res-043a.view' => ['label' => 'View RES-043A Item Validation', 'description' => 'View Research Instrument Item Validation.', 'scope' => 'Assigned scope'],
            'forms.res-043a.validate' => ['label' => 'Validate RES-043A Item Rating', 'description' => 'Submit item-by-item instrument validation rating.', 'scope' => 'Assigned scope'],
            'forms.res-043b.view' => ['label' => 'View RES-043B Validation Summary', 'description' => 'View Research Instrument Validation Rating Summary.', 'scope' => 'Assigned scope'],
            'forms.res-043b.validate' => ['label' => 'Validate RES-043B Rating Summary', 'description' => 'Submit overall instrument validation summary rating.', 'scope' => 'Assigned scope'],
            'forms.res-044.view' => ['label' => 'View RES-044 Data Gathering Endorsement', 'description' => 'View Endorsement for Data Gathering.', 'scope' => 'Group scope'],
            'forms.res-044.endorse' => ['label' => 'Endorse RES-044 Data Gathering', 'description' => 'Issue endorsement for data gathering.', 'scope' => 'Assigned scope'],
            'forms.res-045.view' => ['label' => 'View RES-045 Language Editing Certificate', 'description' => 'View Certificate of Language Editing.', 'scope' => 'Group scope'],
            'forms.res-045.certify' => ['label' => 'Certify RES-045 Language Editing', 'description' => 'Issue certificate of language editing.', 'scope' => 'Assigned scope'],
            'forms.res-046.view' => ['label' => 'View RES-046 Technical Editing Certificate', 'description' => 'View Certificate of Technical Editing.', 'scope' => 'Group scope'],
            'forms.res-046.certify' => ['label' => 'Certify RES-046 Technical Editing', 'description' => 'Issue certificate of technical editing.', 'scope' => 'Assigned scope'],
            'forms.res-047.view' => ['label' => 'View RES-047 Reproduction Endorsement', 'description' => 'View Endorsement for Reproduction.', 'scope' => 'Group scope'],
            'forms.res-047.endorse' => ['label' => 'Endorse RES-047 Reproduction', 'description' => 'Issue endorsement for paper reproduction.', 'scope' => 'Assigned scope'],
            'forms.res-047.approve' => ['label' => 'Approve RES-047 Reproduction', 'description' => 'Record the College Dean approval after adviser endorsement.', 'scope' => 'Assigned class scope'],
            'forms.res-048.view' => ['label' => 'View RES-048 Self and Peer Evaluation', 'description' => 'View Self and Peer Evaluation records.', 'scope' => 'Group scope'],
            'forms.res-048.fill' => ['label' => 'Fill RES-048 Peer Evaluation', 'description' => 'Submit self and peer evaluation ratings.', 'scope' => 'Group scope'],
            'forms.res-049.view' => ['label' => 'View RES-049 Authentic Authorship Certificate', 'description' => 'View Certificate of Authentic Authorship.', 'scope' => 'Group scope'],
            'forms.res-049.sign' => ['label' => 'Sign RES-049 Authentic Authorship', 'description' => 'Sign certificate of authentic authorship.', 'scope' => 'Group scope'],
        ],
    ],
];
