<div x-show="activeOfficialForm === 'RES-036'" x-cloak>
    <x-student-official-form code="RES-Form-036" title="Evaluation of Research Defense" guidebook-page="120">
        <fieldset class="flex flex-wrap gap-6"><legend class="mb-2 font-bold">Type of Defense:</legend><label><input type="radio" name="res_036_defense_type" value="proposal"> Research Proposal Defense</label><label><input type="radio" name="res_036_defense_type" value="final"> Research Final Oral Defense</label></fieldset>
        <div class="grid gap-3 md:grid-cols-3"><label>Date:<input type="date" name="res_036_date" class="w-full"></label><label>Time:<input type="time" name="res_036_time" class="w-full"></label><label>Venue:<input name="res_036_venue" class="w-full"></label></div>
        <label class="block font-bold">Research Title:<input name="res_036_research_title" class="mt-1 w-full font-normal"></label>
        <h3 class="font-bold">I – Research Paper Evaluation</h3>
        <table class="official-form-table text-[10px]"><thead><tr><th>Criteria</th><th class="w-24">Rating</th><th>General Comments / Suggestions</th></tr></thead><tbody>@foreach (['Research Paper Quality (50%)','Originality (25%)','Relevance (25%)'] as $criterion)<tr><td class="font-bold">{{ $criterion }}</td><td><input type="number" min="0" max="100" step="0.01" name="res_036_paper_ratings[]" class="w-full"></td><td><textarea name="res_036_paper_comments[]" class="min-h-16 w-full border-0"></textarea></td></tr>@endforeach<tr><th>Total (100%)</th><td><input type="number" min="0" max="100" step="0.01" name="res_036_paper_total" class="w-full"></td><td></td></tr></tbody></table>
        <h3 class="font-bold">II – Student's Presentation Evaluation</h3>
        <table class="official-form-table text-[10px]"><thead><tr><th>Name of Student Presenter</th><th>Communication Skills (20%)</th><th>Work Organization (30%)</th><th>Effectiveness (50%)</th><th>Total (100%)</th></tr></thead><tbody>@for ($i=1; $i<=4; $i++)<tr><td><input name="res_036_presenters[{{ $i }}][name]" class="w-full"></td>@foreach (['communication','organization','effectiveness','total'] as $score)<td><input type="number" min="0" max="100" step="0.01" name="res_036_presenters[{{ $i }}][{{ $score }}]" class="w-full"></td>@endforeach</tr>@endfor</tbody></table>
        <div class="grid gap-8 pt-8 text-center md:grid-cols-2"><x-official-signature-field name-field="res_036_panelist_printed_name" label="Panelist" /><label>Date:<input type="date" name="res_036_signed_at" class="w-full"></label></div>
    </x-student-official-form>
</div>
