<div x-show="activeOfficialForm === 'RES-037'" x-cloak>
    <x-student-official-form code="RES-Form-037" title="Evaluation Summary of Research Defense" guidebook-page="121">
        <fieldset class="flex flex-wrap gap-6"><legend class="mb-2 font-bold">Type of Defense:</legend><label><input type="radio" name="res_037_defense_type" value="proposal"> Research Proposal Defense</label><label><input type="radio" name="res_037_defense_type" value="final"> Research Final Oral Defense</label></fieldset>
        <div class="grid gap-3 md:grid-cols-3"><label>Date:<input type="date" name="res_037_date" class="w-full"></label><label>Time:<input type="time" name="res_037_time" class="w-full"></label><label>Venue:<input name="res_037_venue" class="w-full"></label></div>
        <label class="block font-bold">Research Title:<input name="res_037_research_title" class="mt-1 w-full font-normal"></label>
        <table class="official-form-table text-[10px]"><thead><tr><th>Area</th><th>Panelist 1</th><th>Panelist 2</th><th>Panelist 3</th><th>Average Rating<br>(1 + 2 + 3) ÷ 3</th><th>Remarks</th></tr></thead><tbody><tr><th class="text-left">I – Research Paper Evaluation (100%)<br><small>Quality, Originality & Relevance</small></th>@for ($i=1; $i<=4; $i++)<td><input type="number" min="0" max="100" step="0.01" name="res_037_paper_scores[]" class="w-full"></td>@endfor<td><textarea name="res_037_paper_remarks" class="min-h-16 w-full border-0"></textarea></td></tr>@for ($student=1; $student<=4; $student++)<tr><th class="text-left">II – Student {{ $student }} Presentation Evaluation (100%)<br><small>Communication Skills, Work Organization & Effectiveness</small><input name="res_037_students[]" class="mt-1 w-full"></th>@for ($i=1; $i<=4; $i++)<td><input type="number" min="0" max="100" step="0.01" name="res_037_student_scores[{{ $student }}][]" class="w-full"></td>@endfor<td><textarea name="res_037_student_remarks[]" class="min-h-12 w-full border-0"></textarea></td></tr>@endfor</tbody></table>
        <div class="grid gap-8 pt-8 text-center md:grid-cols-2"><label>Date Submitted:<input type="date" name="res_037_submitted_at" class="w-full"></label><label><input name="res_037_panelist_signature" class="w-full text-center"><span class="block font-bold">Submitted by (Name & Electronic Signature)</span></label></div>
    </x-student-official-form>
</div>
